export const CARRELLO_ADD_ITEM = "CARRELLO_ADD_ITEM";
export const CARRELLO_REMOVE_ITEM = "CARRELLO_REMOVE_ITEM";
export const CARRELLO_METODO_PAGAMENTO = "CARRELLO_METODO_PAGAMENTO";
export const PULISCI_CARRELLO = "PULISCI_CARRELLO";
