export const CORSO_LIST_REQUEST = "CORSO_LIST_REQUEST";
export const CORSO_LIST_SUCCESS = "CORSO_LIST_SUCCESS";
export const CORSO_LIST_FAIL = "CORSO_LIST_FAIL";

export const CORSO_LATEST_REQUEST = "CORSO_LATEST_REQUEST";
export const CORSO_LATEST_SUCCESS = "CORSO_LATEST_SUCCESS";
export const CORSO_LATEST_FAIL = "CORSO_LATEST_FAIL";

export const CORSO_PROPERTIES_REQUEST = "CORSO_PROPERTIES_REQUEST";
export const CORSO_PROPERTIES_SUCCESS = "CORSO_PROPERTIES_SUCCESS";
export const CORSO_PROPERTIES_FAIL = "CORSO_PROPERTIES_FAIL";

export const ELIMINA_CORSO_REQUEST = "ELIMINA_CORSO_REQUEST";
export const ELIMINA_CORSO_SUCCESS = "ELIMINA_CORSO_SUCCESS";
export const ELIMINA_CORSO_FAIL = "ELIMINA_CORSO_FAIL";

export const CREA_CORSO_REQUEST = "CREA_CORSO_REQUEST";
export const CREA_CORSO_SUCCESS = "CREA_CORSO_SUCCESS";
export const CREA_CORSO_FAIL = "CREA_CORSO_FAIL";
export const CREA_CORSO_RESET = "CREA_CORSO_RESET";

export const CORSO_UPDATE_REQUEST = "CORSO_UPDATE_REQUEST";
export const CORSO_UPDATE_SUCCESS = "CORSO_UPDATE_SUCCESS";
export const CORSO_UPDATE_FAIL = "CORSO_UPDATE_FAIL";
export const CORSO_UPDATE_RESET = "CORSO_UPDATE_RESET";

export const CORSO_UPDATE_RATE_REQUEST = "CORSO_UPDATE_RATE_REQUEST";
export const CORSO_UPDATE_RATE_SUCCESS = "CORSO_UPDATE_RATE_SUCCESS";
export const CORSO_UPDATE_RATE_FAIL = "CORSO_UPDATE_RATE_FAIL";
export const CORSO_UPDATE_RATE_RESET = "CORSO_UPDATE_RATE_RESET";

export const CORSI_MIGLIORI_REQUEST = "CORSI_MIGLIORI_REQUEST";
export const CORSI_MIGLIORI_SUCCESS = "CORSI_MIGLIORI_SUCCESS";
export const CORSI_MIGLIORI_FAIL = "CORSI_MIGLIORI_FAIL";

export const CORSI_ACQUISTATI_REQUEST = "CORSI_ACQUISTATI_REQUEST";
export const CORSI_ACQUISTATI_SUCCESS = "CORSI_ACQUISTATI_SUCCESS";
export const CORSI_ACQUISTATI_FAIL = "CORSI_ACQUISTATI_FAIL";

export const CORSI_CREATI_REQUEST = "CORSI_CREATI_REQUEST";
export const CORSI_CREATI_SUCCESS = "CORSI_CREATI_SUCCESS";
export const CORSI_CREATI_FAIL = "CORSI_CREATI_FAIL";
