export const CORSO_LIST_REQUEST = "CORSO_LIST_REQUEST";
export const CORSO_LIST_SUCCESS = "CORSO_LIST_SUCCESS";
export const CORSO_LIST_FAIL = "CORSO_LIST_FAIL";

export const CORSO_PROPERTIES_REQUEST = "CORSO_PROPERTIES_REQUEST";
export const CORSO_PROPERTIES_SUCCESS = "CORSO_PROPERTIES_SUCCESS";
export const CORSO_PROPERTIES_FAIL = "CORSO_PROPERTIES_FAIL";

export const ELIMINA_CORSO_REQUEST = "ELIMINA_CORSO_REQUEST";
export const ELIMINA_CORSO_SUCCESS = "ELIMINA_CORSO_SUCCESS";
export const ELIMINA_CORSO_FAIL = "ELIMINA_CORSO_FAIL";

export const CREA_CORSO_REQUEST = "CREA_CORSO_REQUEST";
export const CREA_CORSO_SUCCESS = "CREA_CORSO_SUCCESS";
export const CREA_CORSO_FAIL = "CREA_CORSO_FAIL";
export const CREA_CORSO_RESET = "CREA_CORSO_RESET";

export const CORSO_UPDATE_REQUEST = "CORSO_UPDATE_REQUEST";
export const CORSO_UPDATE_SUCCESS = "CORSO_UPDATE_SUCCESS";
export const CORSO_UPDATE_FAIL = "CORSO_UPDATE_FAIL";
export const CORSO_UPDATE_RESET = "CORSO_UPDATE_RESET";
