export const CORSO_LIST_REQUEST = "CORSO_LIST_REQUEST";
export const CORSO_LIST_SUCCESS = "CORSO_LIST_SUCCESS";
export const CORSO_LIST_FAIL = "CORSO_LIST_FAIL";

export const CORSO_PROPERTIES_REQUEST = "CORSO_PROPERTIES_REQUEST";
export const CORSO_PROPERTIES_SUCCESS = "CORSO_PROPERTIES_SUCCESS";
export const CORSO_PROPERTIES_FAIL = "CORSO_PROPERTIES_FAIL";
