export const LEZIONE_PROPERTIES_REQUEST = "LEZIONE_PROPERTIES_REQUEST";
export const LEZIONE_PROPERTIES_SUCCESS = "LEZIONE_PROPERTIES_SUCCESS";
export const LEZIONE_PROPERTIES_FAIL = "LEZIONE_PROPERTIES_FAIL";
