export const LEZIONE_PROPERTIES_REQUEST = "LEZIONE_PROPERTIES_REQUEST";
export const LEZIONE_PROPERTIES_SUCCESS = "LEZIONE_PROPERTIES_SUCCESS";
export const LEZIONE_PROPERTIES_FAIL = "LEZIONE_PROPERTIES_FAIL";

export const LEZIONE_CREA_REQUEST = "LEZIONE_CREA_REQUEST";
export const LEZIONE_CREA_SUCCESS = "LEZIONE_CREA_SUCCESS";
export const LEZIONE_CREA_FAIL = "LEZIONE_CREA_FAIL";
export const LEZIONE_CREA_RESET = "LEZIONE_CREA_RESET";
