export const CREA_ORDINE_REQUEST = "CREA_ORDINE_REQUEST";
export const CREA_ORDINE_SUCCESS = "CREA_ORDINE_SUCCESS";
export const CREA_ORDINE_FAIL = "CREA_ORDINE_FAIL";
export const CREA_ORDINE_RESET = "CREA_ORDINE_RESET";

export const DETTAGLI_ORDINE_REQUEST = "DETTAGLI_ORDINE_REQUEST";
export const DETTAGLI_ORDINE_SUCCESS = "DETTAGLI_ORDINE_SUCCESS";
export const DETTAGLI_ORDINE_FAIL = "DETTAGLI_ORDINE_FAIL";

export const LISTA_MIEI_ORDINI_REQUEST = "LISTA_MIEI_ORDINI_REQUEST";
export const LISTA_MIEI_ORDINI_SUCCESS = "LISTA_MIEI_ORDINI_SUCCESS";
export const LISTA_MIEI_ORDINI_FAIL = "LISTA_MIEI_ORDINI_FAIL";
export const LISTA_MIEI_ORDINI_RESET = "LISTA_MIEI_ORDINI_RESET";
