export const CREA_ORDINE_REQUEST = "CREA_ORDINE_REQUEST";
export const CREA_ORDINE_SUCCESS = "CREA_ORDINE_SUCCESS";
export const CREA_ORDINE_FAIL = "CREA_ORDINE_FAIL";
export const CREA_ORDINE_RESET = "CREA_ORDINE_RESET";

export const DETTAGLI_ORDINE_REQUEST = "DETTAGLI_ORDINE_REQUEST";
export const DETTAGLI_ORDINE_SUCCESS = "DETTAGLI_ORDINE_SUCCESS";
export const DETTAGLI_ORDINE_FAIL = "DETTAGLI_ORDINE_FAIL";
