export const UTENTE_LOGIN_REQUEST = "UTENTE_LOGIN_REQUEST";
export const UTENTE_LOGIN_SUCCESS = "UTENTE_LOGIN_SUCCESS";
export const UTENTE_LOGIN_FAIL = "UTENTE_LOGIN_FAIL";

export const UTENTE_LOGOUT = "UTENTE_LOGOUT";

export const UTENTE_REGISTRAZIONE_REQUEST = "UTENTE_REGISTRAZIONE_REQUEST";
export const UTENTE_REGISTRAZIONE_SUCCESS = "UTENTE_REGISTRAZIONE_SUCCESS";
export const UTENTE_REGISTRAZIONE_FAIL = "UTENTE_REGISTRAZIONE_FAIL";

export const UTENTE_ACCOUNT_REQUEST = "UTENTE_ACCOUNT_REQUEST";
export const UTENTE_ACCOUNT_SUCCESS = "UTENTE_ACCOUNT_SUCCESS";
export const UTENTE_ACCOUNT_FAIL = "UTENTE_ACCOUNT_FAIL";
export const UTENTE_ACCOUNT_RESET = "UTENTE_ACCOUNT_RESET";

export const UTENTE_UPDATE_ACCOUNT_REQUEST = "UTENTE_UPDATE_ACCOUNT_REQUEST";
export const UTENTE_UPDATE_ACCOUNT_SUCCESS = "UTENTE_UPDATE_ACCOUNT_SUCCESS";
export const UTENTE_UPDATE_ACCOUNT_FAIL = "UTENTE_UPDATE_ACCOUNT_FAIL";
export const UTENTE_UPDATE_ACCOUNT_RESET = "UTENTE_UPDATE_ACCOUNT_RESET";

export const LISTA_UTENTI_REQUEST = "LISTA_UTENTI_REQUEST";
export const LISTA_UTENTI_SUCCESS = "LISTA_UTENTI_SUCCESS";
export const LISTA_UTENTI_FAIL = "LISTA_UTENTI_FAIL";
export const LISTA_UTENTI_RESET = "LISTA_UTENTI_RESET";

export const ELIMINA_UTENTE_REQUEST = "ELIMINA_UTENTE_REQUEST";
export const ELIMINA_UTENTE_SUCCESS = "ELIMINA_UTENTE_SUCCESS";
export const ELIMINA_UTENTE_FAIL = "ELIMINA_UTENTE_FAIL";
