const corsi = [
  {
    id: "1",
    title: "Corso 1",
    description: "Descrizione 1",
    difficulty: "Easy",
    summary: "Descrizione breve 1",
    language: "Italiano",
    price: "150",
    accepted: true,
    published: true,
    profit: "150",
    average_rating: "1",
    user_id: "1",
    image: "/images/logo192.png",
  },
  {
    id: "2",
    title: "Corso 2",
    description: "Descrizione 2",
    difficulty: "Easy",
    summary: "Descrizione breve 2",
    language: "Italiano",
    price: "150",
    accepted: true,
    published: true,
    profit: "150",
    average_rating: "2",
    user_id: "2",
    image: "/images/logo192.png",
  },
  {
    id: "3",
    title: "Corso 3",
    description: "Descrizione 3",
    difficulty: "Easy",
    summary: "Descrizione breve 3",
    language: "Italiano",
    price: "150",
    accepted: true,
    published: true,
    profit: "150",
    average_rating: "3",
    user_id: "3",
    image: "/images/logo192.png",
  },
  {
    id: "4",
    title: "Corso 4",
    description: "Descrizione 4",
    difficulty: "Easy",
    summary: "Descrizione breve 4",
    language: "Italiano",
    price: "150",
    accepted: true,
    published: true,
    profit: "150",
    average_rating: "4",
    user_id: "4",
    image: "/images/logo192.png",
  },
  {
    id: "5",
    title: "Corso 5",
    description: "Descrizione 5",
    difficulty: "Easy",
    summary: "Descrizione breve 5",
    language: "Italiano",
    price: "150",
    accepted: true,
    published: true,
    profit: "150",
    average_rating: "5",
    user_id: "5",
    image: "/images/logo192.png",
  },
];

export default corsi;
